# Generated by Django 5.2.3 on 2025-07-07 21:12

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('MP', 'Member of Parliament'), ('Mayor', 'Mayor'), ('Deputy Mayor', 'Deputy Mayor'), ('Ward Chairperson', 'Ward Chairperson')], max_length=50)),
                ('political_party', models.CharField(choices=[('CPN-UML', 'CPN-UML'), ('Nepali Congress', 'Nepali Congress'), ('Maoist', 'Communist Party of Nepal (Maoist Centre)'), ('Samajwadi', 'Samajwadi Party Nepal')], max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward', models.IntegerField()),
                ('profile_picture', models.ImageField(upload_to=myapp.models.candidate_photo_path)),
                ('citizenship_front', models.ImageField(upload_to=myapp.models.candidate_photo_path)),
                ('citizenship_back', models.ImageField(upload_to=myapp.models.candidate_photo_path)),
            ],
            options={
                'db_table': 'candidateprofile',
            },
        ),
        migrations.CreateModel(
            name='DeputymayorVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_email', models.EmailField(max_length=254, unique=True)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('municipality', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Deputyvote',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emailverification',
            },
        ),
        migrations.CreateModel(
            name='KycRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('citizenship_number', models.CharField(max_length=20)),
                ('voter_id', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('ward_no', models.IntegerField()),
                ('photo_front', models.ImageField(upload_to=myapp.models.kyc_photo_path)),
                ('photo_voter', models.ImageField(upload_to=myapp.models.kyc_photo_path)),
                ('photo_citizenship_front', models.ImageField(upload_to=myapp.models.kyc_photo_path)),
                ('photo_citizenship_back', models.ImageField(upload_to=myapp.models.kyc_photo_path)),
                ('face_coordinates', models.JSONField(blank=True, null=True)),
                ('face_descriptor', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kycregistration',
            },
        ),
        migrations.CreateModel(
            name='KycRejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_rejected', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'kycrejected',
            },
        ),
        migrations.CreateModel(
            name='KycRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('citizenship_number', models.CharField(max_length=20)),
                ('voter_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'kycrequests',
            },
        ),
        migrations.CreateModel(
            name='Kycverified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verified_time', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'kycverified',
            },
        ),
        migrations.CreateModel(
            name='MayorVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_email', models.EmailField(max_length=254, unique=True)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('municipality', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Mayourvote',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_header', models.CharField(max_length=255)),
                ('notice_img', models.ImageField(upload_to=myapp.models.get_notice_image_upload_path)),
                ('notice_description', models.TextField()),
            ],
            options={
                'db_table': 'notices',
            },
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo_front', models.ImageField(upload_to=myapp.models.kyc_photo_path)),
            ],
            options={
                'db_table': 'profilepicture',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usersignup',
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'user_registration',
            },
        ),
        migrations.CreateModel(
            name='VoteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'votestatus',
            },
        ),
        migrations.CreateModel(
            name='WardVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_email', models.EmailField(max_length=254, unique=True)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('wardno', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Wardvote',
            },
        ),
        migrations.CreateModel(
            name='MpVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('district', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Mpvote',
                'unique_together': {('voter_email',)},
            },
        ),
    ]
