# Generated by Django 5.2.3 on 2025-07-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='publicaddress',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycregistration',
            name='publicaddress',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
