# Generated by Django 5.2.3 on 2025-06-25 08:39

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_userregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_header', models.CharField(max_length=255)),
                ('notice_img', models.ImageField(upload_to=myapp.models.get_notice_image_upload_path)),
                ('notice_description', models.TextField()),
            ],
            options={
                'db_table': 'notices',
            },
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('photo_front', models.ImageField(upload_to=myapp.models.profile_picture_path)),
            ],
            options={
                'db_table': 'profilepicture',
            },
        ),
    ]
