# Generated by Django 5.2.3 on 2025-07-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_candidateprofile_publicaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycregistration',
            name='descriptor_hash',
            field=models.CharField(default='0x0000000000000000000000000000000000000000000000000000000000000000', max_length=66),
            preserve_default=False,
        ),
    ]
