# Generated by Django 5.2.3 on 2025-07-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_kycregistration_descriptor_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeputymayorVote',
        ),
        migrations.DeleteModel(
            name='MayorVote',
        ),
        migrations.DeleteModel(
            name='MpVote',
        ),
        migrations.DeleteModel(
            name='WardVote',
        ),
    ]
